services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=bookshelfDb'
      - 'MYSQL_PASSWORD=bookshelf'
      - 'MYSQL_ROOT_PASSWORD=bookshelf'
      - 'MYSQL_USER=bookshelf'
    ports:
      - '3307:3306'
    restart: unless-stopped